### ISSUE TITLE
your malloc broke my computer

### ISSUE THREAD

**Issue by eltats** [chicago-industry/malloc#2]
hi, writing this from my phone..
i found your cumstom malloc couple days ago and decided to try it
after trying to allocate 1 char my computer freezed

**Comment by chicago-industry** [comment]
hello! this is impossible. i'm pretty sure this piece of shitty library won't even compile (didn't check, some kind of theorist).
best regards, developer

**Comment by chicago-industry** [comment]
btw nice avatar, bro
